Repository Virtual-Royaume/Royaume-Frontend, pull requests merged in 2023-06, with the labels that each got.

#38 Proposition de changement pour la bordure
  src/app/members/[tag]/layout.tsx
Labels: refactor

#40 Ajout d'un bouton déroulant
  src/app/login/page.tsx
  src/lib/components/atoms/dropdown/profile/dropdown-button.tsx
  src/lib/components/atoms/dropdown/profile/dropdown-link.tsx
  src/lib/components/atoms/dropdown/profile/dropdown-separator.tsx
  src/lib/components/atoms/dropdown/profile/dropdown.tsx
  src/lib/components/atoms/dropdown/profile/dropdown.type.ts
  src/lib/components/atoms/dropdown/profile/index.ts
  src/lib/components/molecules/navbar/navbar.tsx
Labels: feature

#49 Utilisation de Tailwind Merge partout ou besoin
  .vscode/settings.json
  package.json
  src/lib/components/atoms/button/cta/button.tsx
  src/lib/components/atoms/button/cta/button.type.ts
  src/lib/components/atoms/button/link/link.tsx
  src/lib/components/atoms/button/link/link.type.ts
  src/lib/components/atoms/cards/project-cards/new-project-card/new-project-card.tsx
  src/lib/components/atoms/hamburger/hamburger.tsx
  src/lib/components/atoms/little-navbar/little-navbar.tsx
  src/lib/components/atoms/pagination/pagination-item.tsx
  src/lib/components/atoms/texts/heading/heading.tsx
  src/lib/components/atoms/texts/heading/heading.type.ts
  src/lib/components/atoms/texts/text.tsx
  src/lib/components/atoms/texts/text.type.ts
  src/lib/components/molecules/footer/footer.tsx
  src/lib/components/molecules/navbar/navbar.tsx
  src/lib/utils/style/class.ts
Labels: update

#44 Ajout de la page blog
  package.json
  public/images/banner.png
  src/app/blog/[slug]/page.tsx
  src/app/blog/[slug]/page.type.ts
  src/app/blog/[slug]/page.util.ts
  src/lib/components/atoms/cards/blog-post-card/blog-post-card.tsx
  src/lib/components/molecules/content-table/content-table-item.tsx
  src/lib/components/molecules/content-table/content-table.tsx
  src/lib/components/molecules/content-table/content-table.type.ts
  src/lib/components/molecules/content-table/content-table.util.ts
  src/lib/components/molecules/content-table/index.ts
  src/lib/components/molecules/markdown/elements/md-code/index.ts
  src/lib/components/molecules/markdown/elements/md-code/md-code.tsx
  src/lib/components/molecules/markdown/elements/md-code/md-code.type.ts
  src/lib/components/molecules/markdown/elements/md-heading/index.ts
  src/lib/components/molecules/markdown/elements/md-heading/md-heading.tsx
  src/lib/components/molecules/markdown/elements/md-heading/md-heading.type.ts
  src/lib/components/molecules/markdown/index.ts
  src/lib/components/molecules/markdown/markdown-element/index.ts
  src/lib/components/molecules/markdown/markdown-element/markdown-element.tsx
  src/lib/components/molecules/markdown/markdown-element/markdown-element.type.ts
  src/lib/components/molecules/markdown/markdown.tsx
  src/lib/components/molecules/markdown/markdown.type.ts
  src/lib/styles/font.css
  tailwind.config.ts
  test/blog/content-table.spec.ts
Labels: feature

#56 Changement du nom du composant LittleNavbar en Tabs
  package.json
  src/app/members/[tag]/layout.tsx
  src/lib/components/atoms/little-navbar/index.ts
  src/lib/components/atoms/tabs/index.ts
  src/lib/components/atoms/tabs/tabs.tsx
  src/lib/components/atoms/tabs/tabs.type.ts
Labels: refactor

#57 Données réels (nombre de messages)
  src/app/_sections/members.section.tsx
Labels: documentation

#58 Extraction de la couronne et son gradient de couleur
  src/app/_sections/header.section.tsx
  src/app/blog/page.tsx
  src/app/components/crown/crown.tsx
  src/app/components/crown/index.ts
  src/app/members/page.tsx
Labels: refactor
